load("@bazel_skylib//:bzl_library.bzl", "bzl_library")

exports_files([
    "gleescript_main_shim.erl",
    "escript_builder.erl",
    "gleam_eunit_runner.erl",
])

bzl_library(
    name = "gleam_library",
    srcs = ["gleam_library.bzl"],
    visibility = ["//gleam:__subpackages__"],
)

bzl_library(
    name = "gleam_binary",
    srcs = ["gleam_binary.bzl"],
    visibility = ["//gleam:__subpackages__"],
    deps = [":gleam_library"],
)

bzl_library(
    name = "gleam_format_test",
    srcs = ["gleam_format_test.bzl"],
    visibility = ["//gleam:__subpackages__"],
)

bzl_library(
    name = "gleam_release",
    srcs = ["gleam_release.bzl"],
    visibility = ["//gleam:__subpackages__"],
    deps = [
        ":erlang_otp_tree",
        ":gleam_library",
    ],
)

bzl_library(
    name = "gleam_standalone_release",
    srcs = ["gleam_standalone_release.bzl"],
    visibility = ["//gleam:__subpackages__"],
    deps = [
        ":erlang_otp_tree",
        ":gleam_library",
    ],
)

bzl_library(
    name = "erlang_otp_tree",
    srcs = ["erlang_otp_tree.bzl"],
    visibility = ["//gleam:__subpackages__"],
)

bzl_library(
    name = "gleam_test",
    srcs = ["gleam_test.bzl"],
    visibility = ["//gleam:__subpackages__"],
    deps = [":gleam_library"],
)

bzl_library(
    name = "toolchains_repo",
    srcs = ["toolchains_repo.bzl"],
    visibility = ["//gleam:__subpackages__"],
)

bzl_library(
    name = "versions",
    srcs = ["versions.bzl"],
    visibility = ["//gleam:__subpackages__"],
)

bzl_library(
    name = "resolved_toolchain",
    srcs = ["resolved_toolchain.bzl"],
    visibility = ["//gleam:__subpackages__"],
)

bzl_library(
    name = "package_name_check",
    srcs = ["package_name_check.bzl"],
    visibility = ["//gleam:__subpackages__"],
)

bzl_library(
    name = "manifest_toml",
    srcs = ["manifest_toml.bzl"],
    visibility = ["//gleam:__subpackages__"],
)

bzl_library(
    name = "version",
    srcs = ["version.bzl"],
    visibility = ["//gleam:__subpackages__"],
)
