"""Repository rule that exposes a runnable `gleam` binary for the host platform.

`gleam_register_toolchains` (gleam/repositories.bzl) creates one repository per known target
platform (e.g. "gleam1_17_x86_64-unknown-linux-gnu"), plus a `_toolchains` repo wiring them all
into Bazel's toolchain resolution -- neither is meant to be depended on directly, since which one
matches a given machine depends on where Bazel happens to be running. This repository rule picks
the one matching the *host* platform (where `bazel` itself runs, not necessarily a cross-compiled
build's target platform) and re-exposes it under a single, unconditional name, so it can be run
directly without knowing the host's OS/arch string: `bazel run @gleam_host//:gleam -- format`.
"""

load("//gleam/private:toolchains_repo.bzl", "PLATFORMS")

# repository_ctx.os.arch normally matches PLATFORMS' own "aarch64"/"x86_64" naming, but some
# Bazel/OS combinations report "arm64"/"amd64" instead (the same alternate spelling
# erlang/private/hermetic_erlang_repository.bzl normalizes) -- accept both.
_ARCH = {
    "aarch64": "aarch64",
    "arm64": "arm64",
    "x86_64": "x86_64",
    "amd64": "x86_64",
}

def host_platform(repository_ctx):
    """Maps a repository_ctx's os.name/os.arch to a PLATFORMS key.

    Pulled out of _gleam_host_repo_impl so it can be unit-tested (test/unit/host_repo) against
    plain fake structs, without needing a real repository_ctx.

    Args:
        repository_ctx: a repository_ctx, or any struct exposing the same `.os.name`/`.os.arch`
            fields (e.g. a fake used by tests).

    Returns:
        A key of PLATFORMS (gleam/private/toolchains_repo.bzl), e.g. "x86_64-unknown-linux-gnu".
    """
    os_name = repository_ctx.os.name.lower()

    if "windows" in os_name:
        return "x86_64-pc-windows-msvc"

    arch = _ARCH.get(repository_ctx.os.arch)
    if not arch:
        fail("gleam_host: unsupported CPU architecture '{}'".format(repository_ctx.os.arch))

    if "linux" in os_name:
        return "{}-unknown-linux-gnu".format(arch)
    if "mac os" in os_name:
        return "{}-apple-darwin".format(arch)
    fail("gleam_host: unsupported host OS '{}'".format(repository_ctx.os.name))

def _gleam_host_repo_impl(repository_ctx):
    platform = host_platform(repository_ctx)
    if platform not in PLATFORMS:
        fail((
            "gleam_host: resolved host platform '{}' has no matching gleam toolchain " +
            "repository (known platforms: {})"
        ).format(platform, ", ".join(PLATFORMS.keys())))

    user_repository_name = repository_ctx.attr.user_repository_name
    tool_file = "gleam.exe" if platform == "x86_64-pc-windows-msvc" else "gleam"

    build_content = """# Generated by gleam/private:host_repo.bzl
load("@bazel_skylib//rules:native_binary.bzl", "native_binary")

package(default_visibility = ["//visibility:public"])

# The same toolchain instance @{name}_{platform}//:gleam_toolchain resolves to for this host --
# useful for rules that want the ToolchainInfo directly rather than running the CLI.
alias(
    name = "gleam_toolchain",
    actual = "@{name}_{platform}//:gleam_toolchain",
)

# A directly `bazel run`-able gleam CLI for the host platform, e.g.:
#   bazel run @{name}_host//:gleam -- format
native_binary(
    name = "gleam",
    src = "@{name}_{platform}//:{tool_file}",
)
""".format(name = user_repository_name, platform = platform, tool_file = tool_file)

    repository_ctx.file("BUILD.bazel", build_content)

gleam_host_repo = repository_rule(
    implementation = _gleam_host_repo_impl,
    attrs = {
        "user_repository_name": attr.string(
            doc = "Base name shared with the per-platform repositories created by gleam_register_toolchains, e.g. \"gleam1_17\".",
            mandatory = True,
        ),
    },
    doc = "Detects the host platform and re-exposes that platform's gleam toolchain repository under a single, unconditional name.",
)
