"""A minimal, purpose-built parser for Gleam's `manifest.toml` lockfile.

`manifest.toml` is generated by the Gleam build tool (`gleam deps download` / `gleam build`)
and is not meant to be hand-edited, so its `packages` array always uses one compact inline
table per line, e.g.:

    packages = [
      { name = "gleam_stdlib", version = "0.60.0", build_tools = ["gleam"], requirements = [], otp_app = "gleam_stdlib", source = "hex", outer_checksum = "621D600BB134BC239CB2537630899817B1A42E60A1D46C5E9F3FAE39F88C800B" },
    ]

This is not a general TOML parser: it only understands this one specific, stable shape, using
plain string scanning (Starlark has no regex engine and repository/module context strings
cannot be iterated directly, only indexed).
"""

visibility(["//gleam/...", "//test/..."])

def _extract_string(line, key):
    """Returns the value of `key = "..."` in `line`, or None if `key` isn't present."""
    marker = key + " = \""
    idx = line.find(marker)
    if idx == -1:
        return None
    start = idx + len(marker)
    end = line.find("\"", start)
    if end == -1:
        fail("Malformed manifest.toml entry (unterminated string for '{}'): {}".format(key, line))
    return line[start:end]

def _extract_list(line, key):
    """Returns the value of `key = ["a", "b"]` in `line` as a list of strings, or None."""
    marker = key + " = ["
    idx = line.find(marker)
    if idx == -1:
        return None
    start = idx + len(marker)
    end = line.find("]", start)
    if end == -1:
        fail("Malformed manifest.toml entry (unterminated list for '{}'): {}".format(key, line))
    items = []
    for part in line[start:end].split(","):
        part = part.strip()
        if not part:
            continue
        if part.startswith("\"") and part.endswith("\""):
            part = part[1:-1]
        items.append(part)
    return items

def parse_manifest_toml(content):
    """Parses a Gleam `manifest.toml`'s `packages` array.

    Args:
        content: the full text content of a manifest.toml file.

    Returns:
        A list of structs, one per declared package, with fields: name, version, source
        (e.g. "hex", "git", "local"), sha256 (lowercased `outer_checksum`, "" if absent), and
        deps (the package's own `requirements`, i.e. the names of packages it depends on).
    """
    packages = []
    in_packages_block = False
    for raw_line in content.split("\n"):
        line = raw_line.strip()
        if not in_packages_block:
            if line.startswith("packages = [") and not line.endswith("]"):
                in_packages_block = True
            continue

        if line == "]" or line.startswith("]"):
            in_packages_block = False
            continue
        if not line.startswith("{"):
            continue

        name = _extract_string(line, "name")
        version = _extract_string(line, "version")
        if name == None or version == None:
            fail("Malformed manifest.toml package entry (missing name/version): {}".format(line))

        outer_checksum = _extract_string(line, "outer_checksum")
        packages.append(struct(
            name = name,
            version = version,
            source = _extract_string(line, "source"),
            sha256 = outer_checksum.lower() if outer_checksum else "",
            deps = _extract_list(line, "requirements") or [],
        ))
    return packages
