"""Declares the gleam compiler toolchain repositories used by the bzlmod extension.

Dependencies on other modules (bazel_skylib, platforms, etc.) are declared directly in
MODULE.bazel via bazel_dep -- bzlmod is the only supported dependency mode.
"""

load("//gleam/private:toolchains_repo.bzl", "PLATFORMS", "toolchains_repo")
load("//gleam/private:versions.bzl", "TOOL_VERSIONS")

_DOC = "Fetch external tools needed for gleam toolchain"
_ATTRS = {
    "gleam_version": attr.string(mandatory = True, values = TOOL_VERSIONS.keys()),
    "platform": attr.string(mandatory = True, values = PLATFORMS.keys()),
}

def _gleam_repo_impl(repository_ctx):
    platform = repository_ctx.attr.platform

    if platform == "x86_64-pc-windows-msvc":
        download_platform = platform
        extension = "zip"
    else:
        download_platform = platform.replace("gnu", "musl")
        extension = "tar.gz"

    url = "https://github.com/gleam-lang/gleam/releases/download/v{0}/gleam-v{0}-{1}.{2}".format(
        repository_ctx.attr.gleam_version,
        download_platform,
        extension,
    )

    repository_ctx.download_and_extract(
        url = url,
        integrity = TOOL_VERSIONS[repository_ctx.attr.gleam_version][repository_ctx.attr.platform],
    )
    build_content = """# Generated by gleam/repositories.bzl
load("@muchq_rules_gleam//gleam:toolchain.bzl", "gleam_toolchain")

gleam_toolchain(
    name = "gleam_toolchain",
    target_tool = select({
        "@bazel_tools//src/conditions:host_windows": "gleam.exe",
        "//conditions:default": "gleam",
    }),
    erlang_toolchain = "@local_config_erlang//:local_toolchain",
)
"""

    # Base BUILD file for this repository
    repository_ctx.file("BUILD.bazel", build_content)

gleam_repositories = repository_rule(
    _gleam_repo_impl,
    doc = _DOC,
    attrs = _ATTRS,
)

# Wrapper macro around everything above, this is the primary API
def gleam_register_toolchains(name, **kwargs):
    """Convenience macro used by the bzlmod extension (gleam/extensions.bzl) for typical setup.

    - create a repository for each built-in platform like "gleam_linux_amd64"
    - TODO: create a convenience repository for the host platform like "gleam_host"
    - create a repository exposing toolchains for each platform like "gleam_platforms"
    Users can avoid this macro and do these steps themselves, if they want more control.

    Does not itself call native.register_toolchains -- the bzlmod extension's caller does that
    explicitly via MODULE.bazel's own register_toolchains(...), once the extension's
    use_repo(...) call has made the generated repository visible.

    Args:
        name: base name for all created repos, like "gleam1_14"
        **kwargs: passed to each gleam_repositories call
    """
    for platform in PLATFORMS.keys():
        gleam_repositories(
            name = name + "_" + platform,
            platform = platform,
            **kwargs
        )

    toolchains_repo(
        name = name + "_toolchains",
        user_repository_name = name,
    )
