load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "gleam",
    srcs = [
        "gleam_toml.go",
        "lang.go",
    ],
    importpath = "github.com/muchq/rules_gleam/gazelle/gleam",
    visibility = ["//visibility:public"],
    deps = [
        "@com_github_bazelbuild_bazel_gazelle//language",
        "@com_github_bazelbuild_bazel_gazelle//rule",
    ],
)

go_test(
    name = "gleam_test",
    srcs = [
        "gleam_toml_test.go",
        "lang_test.go",
    ],
    embed = [":gleam"],
    deps = [
        "@com_github_bazelbuild_bazel_gazelle//language",
        "@com_github_bazelbuild_bazel_gazelle//rule",
    ],
)
