load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "gleam_gazelle",
    srcs = [
        "gleam_toml.go",
        "lang.go",
    ],
    importpath = "github.com/muchq/rules_gleam/gleam_gazelle",
    visibility = ["//visibility:public"],
    deps = [
        "@bazel_gazelle//language",
        "@bazel_gazelle//rule",
    ],
)

go_test(
    name = "gleam_gazelle_test",
    srcs = [
        "gleam_toml_test.go",
        "golden_test.go",
        "lang_test.go",
    ],
    data = glob(["testdata/golden/**"]),
    embed = [":gleam_gazelle"],
    deps = [
        "@bazel_gazelle//language",
        "@bazel_gazelle//rule",
    ],
)
