name = "my_app"
version = "0.1.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.

[dependencies]
gleam_stdlib = "~> 0.60"

[dev-dependencies]
gleeunit = "~> 1.0"
